### ISSUE TITLE
Create models to capture buoy weather data

### ISSUE THREAD

**Issue by kylejb** [clairBuoyant/server#33]
## What

Encapsulate and persist weather related data that can be captured by buoys.

## How

This task will require, but is not limited to these tasks:
- Create DB model(s) and DTOs (i.e., schemas).
- Create service logic to populate table(s) (would also likely be used by https://github.com/clairBuoyant/server/issues/32 down the road).

## Why

We need to store weather data to minimize requests to NDBC when performing analysis in the future and when providing data to client-side applications.

**Comment by Grieze** [comment]
Commenting to store potential [site for forecast data](https://vlab.noaa.gov/web/mdl/ndfd).

**Comment by kylejb** [comment]
[pybuoy](https://pypi.org/project/pybuoy/) v0.4.0 was recently released to support this task.

See [CHANGELOG](https://github.com/clairBuoyant/pybuoy/blob/main/CHANGELOG.md#040-2022-08-29) for more details. There are breaking changes.
