### ISSUE TITLE
Incorporate weather forecasts from NOAA

### ISSUE THREAD

**Issue by kylejb** [clairBuoyant/server#34]
**Extends and depends on #33** 

## What

Incorporate [NOAA Forecast Database](https://www.ncei.noaa.gov/products/weather-climate-models/national-digital-forecast-database).

## Why

Lays foundation to project future conditions with ML.

**Comment by Grieze** [comment]
[General overview of NDFD docs with definitions](https://www.weather.gov/media/mdl/ndfd/pd01002001curr.pdf)
[Instructions on how to use the NDFD RESTful API](https://graphical.weather.gov/xml/rest.php)

**Comment by Grieze** [comment]
Leaving a note for future use: DTOs are set up in the server codebase, work has no pivoted to implementing the forecasts reading in pybuoy to support future forecast reading in clairbuoyant.

**Comment by kylejb** [comment]
> Leaving a note for future use: DTOs are set up in the server codebase, work has no pivoted to implementing the forecasts reading in pybuoy to support future forecast reading in clairbuoyant.

Related issue: https://github.com/clairBuoyant/pybuoy/issues/17
